
const KEY='lifeTycoonCompact09';const SK=[['tech1','Grundlagen Technik','Technik',1,null],['tech2','Fachwissen','Technik',2,'tech1'],['tech3','Experte','Technik',3,'tech2'],['lead1','Kommunikation','Führung',1,null],['lead2','Teamführung','Führung',2,'lead1'],['lead3','Leadership','Führung',3,'lead2'],['biz1','Verkaufen','Business',1,null],['biz2','Kalkulation','Business',2,'biz1'],['biz3','Unternehmer','Business',3,'biz2'],['fin1','Budget','Finanzen',1,null],['fin2','Investieren','Finanzen',2,'fin1'],['fin3','Vermögensaufbau','Finanzen',3,'fin2']];
function base(){return{version:10,year:1,month:1,age:23,ageMonths:0,xp:0,level:1,cash:8500,invest:1500,debt:0,assets:0,income:2700,fixed:1250,variable:620,savingsPlan:250,risk:'mittel',job:'Metalltechniker',careerLevel:1,performance:48,careerStress:28,careerDone:false,skillPoints:2,skills:{},studyHours:2,studyProgress:0,side:null,business:null,relation:'Single',relationScore:50,partnerIncome:0,kids:0,quality:70,health:82,fitness:48,energy:76,stress:32,vacation:20,eventDone:false,event:null,chronicle:['Start deines Life-Tycoon-Lebens'],history:[10000],annual:[],lastMarket:0,path:{career:0,wealth:0,family:0,balance:0},pending:[],momentum:0,lastOutcome:'Noch keine Langzeitfolge'}}
let s;try{s=Object.assign(base(),JSON.parse(localStorage.getItem(KEY)||'{}'))}catch(e){s=base()}
if(!s.path)s.path={career:0,wealth:0,family:0,balance:0};if(!Array.isArray(s.pending))s.pending=[];if(s.event&&!s.event.id){s.event=null;s.eventDone=false}s.version=10;
function save(){localStorage.setItem(KEY,JSON.stringify(s))}function euro(n){return new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(Math.round(n))}function clamp(n,a=0,b=100){return Math.max(a,Math.min(b,n))}function lvl(){s.level=Math.max(1,Math.floor(s.xp/250)+1)}function sideIncome(){return s.side?Math.round((260+s.side.level*90)*(1+(s.skills.biz1?0.08:0)+(s.skills.biz2?0.1:0))):0}function bizIncome(){return s.business?Math.round((s.business.base+s.business.level*180)*(1+(s.skills.biz2?0.12:0)+(s.skills.biz3?0.18:0))):0}function partnerShare(){return s.relation==='Verheiratet'||s.relation==='Verlobt'||s.relation==='Beziehung'?Math.round(s.partnerIncome*.36):0}function kidCost(){return s.kids*260}function loanCost(){return s.debt>0?Math.min(420,Math.round(s.debt*.018)):0}function flow(){return s.income+sideIncome()+bizIncome()+partnerShare()-s.fixed-s.variable-kidCost()-loanCost()-s.savingsPlan}function net(){return s.cash+s.invest+s.assets+(s.business?s.business.value:0)-s.debt}function workHours(){return 40+(s.side?7+s.side.level:0)+(s.business?8+s.business.level*2:0)}function freeHours(){return Math.max(0,168-56-workHours()-5-s.studyHours-(s.kids*5)-(s.relation!=='Single'?5:0))}function balanceScore(){return Math.round((s.health+s.fitness+s.energy+(100-s.stress))/4)}function lifeScore(){let f=clamp(55+flow()/55),c=clamp(s.performance),b=balanceScore();return Math.round((f+c+s.quality+b)/4)}function skillCount(){return Object.values(s.skills).filter(Boolean).length}
function absMonth(){return(s.year-1)*12+s.month}function pathAdd(k,n){s.path[k]=Math.max(0,(s.path[k]||0)+n)}function currentPath(){let map={career:'Karriere-Mensch',wealth:'Vermögensbauer',family:'Familienmensch',balance:'Ausgeglichen'};let a=Object.entries(s.path).sort((x,y)=>y[1]-x[1]);if(!a.length||a[0][1]<3)return{key:'open',label:'Noch offen'};if(a[1]&&a[0][1]-a[1][1]<2)return{key:'mix',label:'Vielseitig'};return{key:a[0][0],label:map[a[0][0]]}}
function pathPerk(){let p=currentPath().key;if(p==='career')s.performance=clamp(s.performance+1);if(p==='wealth'&&s.invest>0)s.invest*=1.0007;if(p==='family'&&s.relation!=='Single')s.relationScore=clamp(s.relationScore+1);if(p==='balance'){s.stress=clamp(s.stress-1);s.energy=clamp(s.energy+1)}}
function eventLabel(id){let x={delayedBill:'Verschobene Rechnung',bossProject:'Schlüsselprojekt',bossResult:'Projektabschluss',bizFollowup:'Großkunde meldet sich',familyTalk:'Gespräch über Zukunft',burnout:'Körper zieht die Notbremse'};return x[id]||'Offene Folge'}
function schedule(id,months,meta={}){s.pending.push({id,due:absMonth()+months,meta});s.lastOutcome=`Folge geplant: ${eventLabel(id)}`}function takeDue(){let i=s.pending.findIndex(x=>x.due<=absMonth());if(i<0)return null;let p=s.pending.splice(i,1)[0];return{id:p.id,meta:p.meta||{},chain:true}}
function hasPending(id){return s.pending.some(x=>x.id===id)}
function showView(btn){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.nav button').forEach(x=>x.classList.remove('active'));document.getElementById(btn.dataset.v).classList.add('active');btn.classList.add('active');render()}function toast(t){let x=document.getElementById('toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),1800)}function openM(t,h){modalTitle.textContent=t;modalBody.innerHTML=h;modal.classList.add('show')}function closeModal(){modal.classList.remove('show')}
