function chooseEvent(){let due=takeDue();if(due)return due;let pool=['bill','jobGood','taxRefund','friendTrip','rentRise'];if(s.stress>65)pool.push('stressWarn','sickDay');if(s.kids>0)pool.push('familyWeekend');if(s.business)pool.push('bizClient');if(s.invest>4000)pool.push('market');if(s.debt>5000)pool.push('debtPressure');if(skillCount()>=3)pool.push('mentor');if(s.relation!=='Single'&&s.relationScore<58)pool.push('relationshipTension');if(s.side)pool.push('sideOpportunity');if(s.momentum>=2)pool.push('jobGood','taxRefund','mentor');return{id:pool[Math.floor(Math.random()*pool.length)],meta:{}}}
function eventObject(ev){let m=ev.meta||{};switch(ev.id){
case'bill':return{t:'Unerwartete Rechnung',d:'Eine Reparatur kostet 420 €. Was machst du?',a:[['Jetzt bezahlen',()=>{s.cash-=420;s.stress+=4;pathAdd('wealth',1)}],['Verschieben',()=>{s.quality-=2;s.stress+=7;schedule('delayedBill',2);pathAdd('career',1)}]]};
case'delayedBill':return{t:'Die Rechnung ist zurück',d:'Aus 420 € sind durch Mahnkosten 560 € geworden.',a:[['560 € bezahlen',()=>{s.cash-=560;s.stress-=2;pathAdd('wealth',1)}],['Finanzieren',()=>{s.debt+=560;s.stress+=6;pathAdd('wealth',-1)}]]};
case'jobGood':return{t:'Gute Woche im Job',d:'Deine Leistung fällt positiv auf. Der Chef deutet ein wichtiges Projekt an.',a:[['Extra Einsatz',()=>{s.performance+=8;s.stress+=5;s.xp+=40;pathAdd('career',2);schedule('bossProject',2)}],['Balance halten',()=>{s.performance+=3;s.energy+=5;s.xp+=20;pathAdd('balance',2)}]]};
case'bossProject':return{t:'Das Schlüsselprojekt',d:'Der Chef will, dass du ein schwieriges Projekt übernimmst. Erfolg könnte deine Karriere beschleunigen.',a:[['Verantwortung übernehmen',()=>{s.performance+=10;s.stress+=12;s.xp+=60;pathAdd('career',3);schedule('bossResult',2,{lead:true})}],['Ablehnen',()=>{s.stress-=5;s.energy+=5;pathAdd('balance',2)}]]};
case'bossResult':return{t:'Projekt abgeschlossen',d:'Das Schlüsselprojekt ist geschafft. Jetzt entscheidest du, was du aus dem Erfolg machst.',a:[['Bonus verhandeln',()=>{let b=s.skills.lead1?900:550;s.cash+=b;s.performance+=8;s.xp+=70;pathAdd('career',2);s.chronicle.unshift(`Projektbonus ${euro(b)}`)}],['Freizeit nehmen',()=>{s.stress-=16;s.energy+=12;s.quality+=4;pathAdd('balance',3)}]]};
case'stressWarn':return{t:'Warnsignal',d:'Dein Stresslevel ist zu hoch. Noch kannst du gegensteuern.',a:[['Tempo rausnehmen',()=>{s.stress-=18;s.performance-=3;pathAdd('balance',2)}],['Durchziehen',()=>{s.stress+=10;s.health-=7;s.xp+=25;pathAdd('career',2);if(!hasPending('burnout'))schedule('burnout',2)}]]};
case'burnout':return{t:'Dein Körper zieht die Notbremse',d:'Die letzten Monate waren zu viel. Du brauchst eine Entscheidung.',a:[['Erholung priorisieren',()=>{s.stress-=28;s.energy+=20;s.health+=8;s.performance-=7;pathAdd('balance',4)}],['Weiter funktionieren',()=>{s.health-=14;s.energy-=15;s.performance+=3;s.quality-=5;pathAdd('career',2)}]]};
case'familyWeekend':return{t:'Familienwochenende',d:'Die Familie möchte gemeinsam etwas unternehmen.',a:[['Ausflug · 180 €',()=>{s.cash-=180;s.quality+=7;s.relationScore+=5;pathAdd('family',2);if(s.relation!=='Single')schedule('familyTalk',2)}],['Zu Hause',()=>{s.quality+=3;pathAdd('balance',1)}]]};
case'familyTalk':return{t:'Gespräch über eure Zukunft',d:'Die letzten gemeinsamen Monate haben die Frage aufgeworfen: Wie ernst soll es werden?',a:[['Nähe zulassen',()=>{s.relationScore+=10;s.quality+=5;s.fixed=Math.max(500,s.fixed-80);pathAdd('family',3);s.chronicle.unshift('Gemeinsamer Zukunftsschritt')}],['Noch Zeit lassen',()=>{s.relationScore-=3;s.stress-=4;pathAdd('balance',1)}]]};
case'bizClient':return{t:'Neuer Großkunde',d:'Ein Kunde bietet dir einen größeren Auftrag an.',a:[['Annehmen',()=>{s.cash+=700+s.business.level*160;s.stress+=10;s.business.value+=400;pathAdd('wealth',2);schedule('bizFollowup',2)}],['Ablehnen',()=>{s.stress-=2;pathAdd('balance',1)}]]};
case'bizFollowup':return{t:'Der Großkunde kommt zurück',d:'Aus dem Auftrag könnte eine dauerhafte Geschäftsbeziehung werden.',a:[['900 € reinvestieren',()=>{if(s.cash>=900){s.cash-=900;s.business.level++;s.business.value+=1500;s.stress+=6;s.xp+=90;pathAdd('wealth',3)}else{s.debt+=900;s.business.value+=900;s.stress+=9;pathAdd('wealth',1)}}],['Klein halten',()=>{s.cash+=350;s.stress-=3;pathAdd('balance',1)}]]};
case'market':return{t:'Unruhiger Markt',d:`Dein Depot ist ${euro(s.invest)} wert und schwankt stärker als gewöhnlich.`,a:[['Ruhe bewahren',()=>{s.xp+=25;pathAdd('wealth',2)}],['500 € verkaufen',()=>{let q=Math.min(500,s.invest);s.invest-=q;s.cash+=q;pathAdd('balance',1)}]]};
case'taxRefund':return{t:'Unerwartetes Plus',d:'Du bekommst 360 € zurück. Was machst du damit?',a:[['Investieren',()=>{s.invest+=360;pathAdd('wealth',2);s.xp+=20}],['Genießen',()=>{s.cash+=110;s.quality+=6;pathAdd('balance',2)}]]};
case'friendTrip':return{t:'Spontaner Wochenendtrip',d:'Freunde laden dich ein. Kosten: etwa 320 €.',a:[['Mitfahren',()=>{s.cash-=320;s.quality+=8;s.stress-=7;pathAdd('balance',2)}],['Absagen',()=>{s.cash+=0;s.quality-=1;pathAdd('wealth',1)}]]};
case'rentRise':return{t:'Lebenskosten steigen',d:'Deine laufenden Kosten würden um 90 € pro Monat steigen.',a:[['Akzeptieren',()=>{s.fixed+=90;s.stress+=3}],['Anderswo sparen',()=>{s.variable=Math.max(250,s.variable-80);s.quality-=3;pathAdd('wealth',1)}]]};
case'sickDay':return{t:'Du fühlst dich ausgelaugt',d:'Heute wäre eigentlich ein wichtiger Arbeitstag.',a:[['Krank melden',()=>{s.energy+=10;s.health+=5;s.performance-=2;pathAdd('balance',2)}],['Trotzdem arbeiten',()=>{s.performance+=4;s.energy-=10;s.health-=5;pathAdd('career',1)}]]};
case'debtPressure':return{t:'Schulden drücken',d:`Deine Restschuld liegt bei ${euro(s.debt)}.`,a:[['500 € sondertilgen',()=>{let q=Math.min(500,s.cash,s.debt);s.cash-=q;s.debt-=q;pathAdd('wealth',2)}],['Liquidität behalten',()=>{s.stress+=3;pathAdd('balance',1)}]]};
case'mentor':return{t:'Mentor bietet Hilfe an',d:'Eine erfahrene Person nimmt sich Zeit für deine Entwicklung.',a:[['Lernen',()=>{s.studyProgress+=12;s.performance+=3;s.xp+=35;pathAdd('career',1)}],['Netzwerk nutzen',()=>{s.performance+=5;s.quality+=2;s.xp+=25;pathAdd('career',2)}]]};
case'relationshipTension':return{t:'Spannungen zu Hause',d:'Deine Beziehung leidet unter Zeitdruck und Stress.',a:[['Zeit investieren',()=>{s.cash-=90;s.relationScore+=10;s.stress-=4;pathAdd('family',2)}],['Arbeit geht vor',()=>{s.relationScore-=9;s.performance+=3;pathAdd('career',2)}]]};
case'sideOpportunity':return{t:'Chance im Nebenverdienst',d:'Ein zusätzlicher Auftrag könnte dein Nebeneinkommen steigern.',a:[['Auftrag annehmen',()=>{s.cash+=260*s.side.level;s.stress+=6;s.xp+=25;pathAdd('wealth',1)}],['Freizeit schützen',()=>{s.energy+=5;s.stress-=5;pathAdd('balance',2)}]]};
default:return eventObject({id:'bill',meta:{}})}}
function renderEvent(){if(!s.event)s.event=chooseEvent();let e=eventObject(s.event);eventCard.innerHTML=`<h3>${e.t}</h3><div class="mut">${e.d}</div><div class="actions">${e.a.map((a,i)=>`<button class="btn ${i===0?'primary':'ghost'}" onclick="eventChoice(${i})">${a[0]}</button>`).join('')}</div>`;if(s.eventDone)eventCard.innerHTML=`<h3>✓ ${e.t}</h3><div class="mut">${s.lastOutcome||'Die Entscheidung wird sich auf dein weiteres Leben auswirken.'}</div>`}
function eventChoice(i){if(s.eventDone)return;let e=eventObject(s.event),a=e.a[i];a[1]();s.eventDone=true;s.lastOutcome=`${e.t}: ${a[0]}`;s.xp+=15;s.stress=clamp(s.stress);s.health=clamp(s.health);s.energy=clamp(s.energy);s.quality=clamp(s.quality);s.relationScore=clamp(s.relationScore);save();render();toast('Entscheidung gespeichert')}
function nextMonth(){if(!s.eventDone)return toast('Triff zuerst deine Monatsentscheidung');let f=flow();s.cash+=f+s.savingsPlan;if(s.savingsPlan>0&&s.cash>=s.savingsPlan){s.cash-=s.savingsPlan;s.invest+=s.savingsPlan}let r={niedrig:.002,mittel:.005,hoch:.009}[s.risk]||.005;let skillBoost=s.skills.fin2?.0007:0;let swing=(Math.random()-.44)*(r+skillBoost)*3;s.lastMarket=swing;s.invest*=1+swing;if(s.debt>0){let p=Math.min(s.debt,Math.max(90,loanCost()*.7));s.debt-=p}s.ageMonths++;if(s.ageMonths>=12){s.age++;s.ageMonths=0;s.chronicle.unshift(`${s.age}. Geburtstag`)}s.studyProgress+=s.studyHours;if(s.studyProgress>=28){s.studyProgress-=28;s.skillPoints++;s.xp+=35;toast('+1 Skillpunkt')}let over=freeHours()<10;s.stress=clamp(s.stress+(over?8:-2)+(s.studyHours>=8?3:0));s.energy=clamp(s.energy+(s.stress>70?-7:2));if(s.stress>78)s.health=clamp(s.health-4);if(s.fitness>60)s.health=clamp(s.health+1);s.performance=clamp(s.performance+(s.energy>55?2:-3));s.relationScore=clamp(s.relationScore+(s.relation==='Single'?0:(s.stress>70?-3:1)));s.quality=clamp(s.quality+(f>500?1:0)-(f<0?2:0));pathPerk();let good=f>250&&balanceScore()>=60,bad=f<0||s.stress>75||s.health<55;if(good)s.momentum=clamp(s.momentum+1,-5,5);else if(bad)s.momentum=clamp(s.momentum-1,-5,5);else s.momentum+=s.momentum>0?-1:s.momentum<0?1:0;if(s.stress>88&&!hasPending('burnout'))schedule('burnout',1);s.xp+=30;s.month++;if(s.month>12){s.month=1;s.year++;s.annual.unshift({y:s.year-1,net:net(),score:lifeScore(),path:currentPath().label,momentum:s.momentum});s.chronicle.unshift(`Jahr ${s.year-1} abgeschlossen · ${currentPath().label} · Vermögen ${euro(net())}`)}s.history.push(net());if(s.history.length>12)s.history.shift();s.event=null;s.eventDone=false;s.careerDone=false;lvl();save();render();toast(`Monat abgeschlossen · ${f>=0?'+':''}${euro(f)}`)}
